const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Behaviors.Orbit,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Jumpthru: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{bad: 0},
	{TiledBackground3: 0},
	{Orbit: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{TiledBackground4: 0},
	{Pathfinding: 0},
	{Sprite4: 0},
	{DragDrop: 0},
	{bomb: 0},
	{Sprite6: 0},
	{coin: 0},
	{ScoreText: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Fade: 0},
	{Sprite11: 0},
	{Rotate: 0},
	{Sprite12: 0},
	{start2: 0},
	{bomb2: 0},
	{egg: 0},
	{kaboom: 0},
	{level2End: 0},
	{level3Start: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{Sprite5: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{TiledBackground9: 0},
	{Sprite17: 0},
	{TiledBackground10: 0},
	{Text: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Score: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	bad: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	start2: class extends self.ISpriteInstance {},
	bomb2: class extends self.ISpriteInstance {},
	egg: class extends self.ISpriteInstance {},
	kaboom: class extends self.ISpriteInstance {},
	level2End: class extends self.ISpriteInstance {},
	level3Start: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {}
}