const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Follow,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Sprite: 0},
	{Keyboard: 0},
	{Sprite2: 0},
	{Bullet: 0},
	{Sprite3: 0},
	{Text: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{bb97a4d608b9dde020d504f: 0},
	{Text2: 0},
	{LocalStorage: 0},
	{Sprite6: 0},
	{badBoy: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Solid: 0},
	{LineOfSight: 0},
	{Pathfinding: 0},
	{Follow: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Text3: 0},
	{Text4: 0},
	{Text5: 0},
	{Preview: 0},
	{Sprite14: 0},
	{Score: 0},
	{randheight: 0},
	{powerup2: 0},
	{powerup1: 0},
	{Highscore: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	bb97a4d608b9dde020d504f: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	badBoy: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Preview: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}