const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Timeline,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.gamepad,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Timeline.Exps.TotalTime,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Particles.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{GroundCollision: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerCollision: 0},
	{Keyboard: 0},
	{BridgePiece: 0},
	{Trigger: 0},
	{Timeline: 0},
	{WaterDrops: 0},
	{Background: 0},
	{River: 0},
	{ForegroundGround: 0},
	{PlayerAreaLight: 0},
	{Tween: 0},
	{Vegetation: 0},
	{Fireflies: 0},
	{CaveHumidity: 0},
	{Bubble: 0},
	{Steam: 0},
	{ForegroundSpikes: 0},
	{Fog: 0},
	{DustTrail: 0},
	{Gamepad: 0},
	{PlayerAnimations: 0},
	{WaterSplash: 0},
	{Sine: 0},
	{PlantAreaLight: 0},
	{BigPlant: 0},
	{InvisibleWall: 0}
];

self.InstanceType = {
	GroundCollision: class extends self.ITilemapInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BridgePiece: class extends self.ISpriteInstance {},
	Trigger: class extends self.ISpriteInstance {},
	Timeline: class extends self.IInstance {},
	WaterDrops: class extends self.IParticlesInstance {},
	Background: class extends self.ISpriteInstance {},
	River: class extends self.ISpriteInstance {},
	ForegroundGround: class extends self.ISpriteInstance {},
	PlayerAreaLight: class extends self.ISpriteInstance {},
	Vegetation: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	CaveHumidity: class extends self.IParticlesInstance {},
	Bubble: class extends self.ISpriteInstance {},
	Steam: class extends self.IParticlesInstance {},
	ForegroundSpikes: class extends self.ISpriteInstance {},
	Fog: class extends self.ITiledBackgroundInstance {},
	DustTrail: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	PlayerAnimations: class extends self.ISpriteInstance {},
	WaterSplash: class extends self.IParticlesInstance {},
	PlantAreaLight: class extends self.ISpriteInstance {},
	BigPlant: class extends self.ISpriteInstance {},
	InvisibleWall: class extends self.ISpriteInstance {}
}