const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.LOS,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Solid: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{DestroyOutside: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Keyboard: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{score: 0},
	{Bullet: 0},
	{Wrap: 0},
	{canonBalls: 0},
	{Bullet2: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Text: 0},
	{LineOfSight: 0},
	{Sprite30: 0},
	{Pin: 0},
	{Sprite31: 0},
	{Mouse: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite36: 0},
	{gun: 0},
	{Sprite: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{special: 0},
	{Sprite2: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Text2: 0}
];

self.InstanceType = {
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	canonBalls: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	gun: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	special: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {}
}