const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Tilemap,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Invincible: 0},
	{Attacking: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Pirate: 0},
	{Solid: 0},
	{Sand: 0},
	{Gate: 0},
	{Keyboard: 0},
	{ScoreText: 0},
	{Coin: 0},
	{Sun: 0},
	{Fire: 0},
	{TiledBackground3: 0},
	{End: 0},
	{Restart: 0},
	{Ice: 0},
	{Waves: 0},
	{Background: 0},
	{Text: 0},
	{Stones: 0},
	{LocalStorage: 0},
	{Text2: 0},
	{Tilemap: 0},
	{BossLives: 0},
	{CanBeHit: 0},
	{Boss: 0},
	{Text3: 0},
	{Bullet: 0},
	{Cannonball: 0},
	{SwordHitbox: 0},
	{PirateLives: 0},
	{Text4: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Victory: 0},
	{ScoreText2: 0},
	{Text5: 0},
	{Score: 0},
	{Highscore: 0},
	{PlayerLives: 0}
];

self.InstanceType = {
	Pirate: class extends self.ISpriteInstance {},
	Sand: class extends self.ITiledBackgroundInstance {},
	Gate: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	Coin: class extends self.ISpriteInstance {},
	Sun: class extends self.ITiledBackgroundInstance {},
	Fire: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	End: class extends self.ITextInstance {},
	Restart: class extends self.ITextInstance {},
	Ice: class extends self.ITiledBackgroundInstance {},
	Waves: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Stones: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Boss: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Cannonball: class extends self.ISpriteInstance {},
	SwordHitbox: class extends self.ISpriteInstance {},
	PirateLives: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Victory: class extends self.ITextInstance {},
	ScoreText2: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {}
}